_BASE_: "../Base-CondInst.yaml"
MODEL:
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 0.5
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: True
      INSTANCES_CONFIDENCE_THRESH: 0.45
      OVERLAP_THRESH: 0.4
  CONDINST:
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: True # true for panoptic
DATASETS:
  TRAIN: ("coco_2017_train_pano_instance_panoptic_separated",) # ("coco_2017_trainxxx_panoptic_separated",)
  TEST: ("coco_2017_val_panoptic_separated",)
INPUT:
  MASK_FORMAT: "bitmask"  # default: "polygon" use bitmask for pano instance