_BASE_: "Base-Panoptic.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  SEM_SEG_HEAD:
    NUM_CLASSES: 19
OUTPUT_DIR: "output/panoptic/CondInst/R_50_1x"
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TEST: 2048

  MASK_FORMAT: "polygon"
DATASETS:
  TRAIN: ("cityscapes_fine_panoptic_seg_train",)
  TEST: ("cityscapes_fine_panoptic_seg_val",)
SOLVER:
  BASE_LR: 0.01
  STEPS: (40000, 55000)
  MAX_ITER: 65000
  IMS_PER_BATCH: 32

#  CHECKPOINT_PERIOD: 200


TEST:
  EVAL_PERIOD: 8000