_BASE_: "Base-FCOS.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True



INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/fcos/R_50_1x"
#SOLVER:
#  IMS_PER_BATCH: 1
#DATALOADER:
#  NUM_WORKERS: 0

