MODEL:
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
  CONDINST:
    MAX_PROPOSALS_PER_IM: 64
    MAX_PROPOSALS: 500
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: False # adjustments original is False
  PANOPTIC_FPN:
    COMBINE:
      ENABLED: False

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)  # ("coco_2017_test-dev",)   #
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
#DATALOADER:
#  NUM_WORKERS: 0